"""Defaults and constants used by the naming convention function."""

DEFAULT_PREFIX_SEPARATOR = "/"
ANNOTATION_PREFIX = "function-naming-convention"
ANNOTATION_INCLUDE_EXTERNAL_NAME = f"{ANNOTATION_PREFIX}{DEFAULT_PREFIX_SEPARATOR}external-name"
ANNOTATION_INCLUDE_FORPROVIDER_NAME = (
    f"{ANNOTATION_PREFIX}{DEFAULT_PREFIX_SEPARATOR}for-provider-name"
)
ANNOTATION_INCLUDE_LABELS_AS_TAGS = f"{ANNOTATION_PREFIX}{DEFAULT_PREFIX_SEPARATOR}labels-as-tags"
ANNOTATION_INCLUDE_TAG_NAME_ANNOTATION = f"{ANNOTATION_PREFIX}{DEFAULT_PREFIX_SEPARATOR}tag-name"
ANNOTATION_FORPROVIDER_NAME_FIELD = (
    f"{ANNOTATION_PREFIX}{DEFAULT_PREFIX_SEPARATOR}for-provider-name-field"
)
ANNOTATION_FORPROVIDER_NAMEOVERRIDE = (
    f"{ANNOTATION_PREFIX}{DEFAULT_PREFIX_SEPARATOR}for-provider-nameoverride"
)
ANNOTATION_NAME_TEMPLATE = f"{ANNOTATION_PREFIX}{DEFAULT_PREFIX_SEPARATOR}name-template"
ANNOTATION_NAME_TEMPLATE_SEPARATOR = (
    f"{ANNOTATION_PREFIX}{DEFAULT_PREFIX_SEPARATOR}name-fields-separator"
)
ANNOTATION_REPLICATE_LABELS_TO = f"{ANNOTATION_PREFIX}{DEFAULT_PREFIX_SEPARATOR}labels-to-field"
ANNOTATION_SKIP_NAME_MODIFY = f"{ANNOTATION_PREFIX}{DEFAULT_PREFIX_SEPARATOR}skip-name-modify"
ANNOTATION_TAGS_FIELD = f"{ANNOTATION_PREFIX}{DEFAULT_PREFIX_SEPARATOR}tags-field"
CONTEXT_KEY_ENVIRONMENT = "apiextensions.crossplane.io/environment"
DEFAULT_MAPPED_VALUE = "dflt"
DEFAULT_MAPPED_VALUE_MAX_LENGTH = 4
DEFAULT_NAME_TEMPLATE_SEPARATOR = "-"
ALLOWED_TEMPLATE_SEPARATORS = {"-", "."}
INPUT_ANNOTATIONS = "annotations"
INPUT_CONTEXT = "context"
INPUT_ENV_TO_LABEL = "envToLabel"
INPUT_KEBAB_CASE_LABELS_AND_TAGS = "kebabCaseLabelsAndTags"
INPUT_LABELS = "labels"
INPUT_LABELS_AS_TAGS = "labelsAsTags"
INPUT_MAPPED_VALUES = "valuesFromMap"
INPUT_NAME_TEMPLATE = "nameTemplateFields"
INPUT_PREFIX = "prefix"
INPUT_SEPARATOR = "separator"
INPUT_TAGS = "tags"
INPUT_TAGS_FIELD = "tagsField"
INPUT_TEMPLATE_ITEMS_SEPARATOR = "templateItemsSeparator"
INPUT_VALUES = "values"
MAX_PREFIXED_NAME_LENGTH = 253
MAX_NAME_LENGTH = 63
