---
name: Function lint and validate

defaults:
  run:
    shell: bash

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: "3.14.3"

permissions:
  contents: read
  pull-requests: write

jobs:
  lookup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v6
        with:
          fetch-depth: 1

      - name: Get changed folders
        id: lookup
        uses: tj-actions/changed-files@9426d40962ed5378910ee2e21d5f8c6fcbf2dd96 # v47.0.6
        with:
          files_yaml: |
            docs:
              - '**/*.md'
            function:
              - '!**/package/input/inputs.yaml'
              - '!*.md'
            inputs:
              - '**/package/input/inputs.yaml'
              - '!*.md'
            yaml:
              - '**/*.yaml'
              - '**/*.yml'
    outputs:
      docs: ${{ steps.lookup.outputs.docs_any_changed }}
      function: ${{ steps.lookup.outputs.function_any_changed }}
      inputs: ${{ steps.lookup.outputs.inputs_any_changed }}
      yaml: ${{ steps.lookup.outputs.yaml_any_changed }}

  validate-function:
    needs: lookup
    runs-on: ubuntu-latest
    if: ${{
      needs.lookup.outputs.function == 'true' &&
      github.event_name == 'pull_request' && github.event.pull_request.merged != true
      }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v6

      - name: Setup Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Restore cached tools
        id: cache-tools-restore
        uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
        with:
          path: .tools
          key: ${{ runner.os }}-tools-${{ hashFiles('**/versions.mk') }}

      - name: Validate function
        run: make validate

      - name: Cache tools
        id: cache-tools-save
        uses: actions/cache/save@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
        with:
          path: .tools
          key: ${{ steps.cache-tools-restore.outputs.cache-primary-key }}

  validate-inputs:
    needs: lookup
    runs-on: ubuntu-latest
    if: ${{
      needs.lookup.outputs.inputs == 'true' &&
      github.event_name == 'pull_request' && github.event.pull_request.merged != true
      }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v6

      - name: Restore cached tools
        id: cache-tools-restore
        uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
        with:
          path: .tools
          key: ${{ runner.os }}-tools-${{ hashFiles('**/versions.mk') }}

      - name: Validate inputs
        run: make validate-inputs

      - name: Cache tools
        uses: actions/cache/save@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
        with:
          path: .tools
          key: ${{ steps.cache-tools-restore.outputs.cache-primary-key }}

  lint-docs:
    needs: lookup
    runs-on: ubuntu-latest
    if: ${{
      needs.lookup.outputs.docs == 'true' &&
      github.event_name == 'pull_request' && github.event.pull_request.merged != true
      }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v6

      - name: Lint Markdown
        uses: actionshub/markdownlint@6c82ff529253530dfbf75c37570876c52692835f # v3.1.4
        with:
          filesToIgnoreRegex: (\..*\/.*)$

  yaml-lint:
    runs-on: ubuntu-latest
    needs: lookup
    if: ${{
      needs.lookup.outputs.yaml == 'true' &&
      github.event_name == 'pull_request' && github.event.pull_request.merged != true
      }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v6

      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: pip

      - run: pip install yamllint

      - id: yaml-lint
        name: YAML lint
        run: yamllint .
